# Example Production Database Configuration
# Copy this file and rename to your database name (e.g., production.yaml)

# Database connection settings
database:
  # Database name (must match the actual database name)
  name: production
  
  # PostgreSQL server hostname or IP address
  host: prod-db-server.company.com
  
  # PostgreSQL server port (default: 5432)
  port: 5432
  
  # Database username for backup operations
  username: backup_user
  
  # Database password (use strong, secure passwords for production)
  password: "your_secure_production_password"
  
  # Enable this database for backup operations
  enabled: true
  
  # Include this database in automatic backup (cron jobs)
  auto_backup: true

# Database-specific backup settings
backup:
  # Directory for storing backup files (use absolute path for production)
  output_dir: /var/backups/postgresql/production
  
  # Backup format: 'custom' (binary, recommended) or 'plain' (SQL text)
  format: custom
  
  # Enable compression for backup files
  compress: true
  
  # Advanced retention policy for production database
  retention:
    # Local storage retention policy (shorter for production due to space constraints)
    local:
      # Daily backups: keep for 30 days
      daily: 30
      # Weekly backups: keep for 90 days
      weekly: 90
      # Monthly backups: keep for 12 months
      monthly: 365  # 12 months
      # Delete everything older than 12 months
      max_age: 365  # 12 months
    
    # Remote storage retention policy (longer for production)
    remote:
      # Daily backups: keep for 60 days
      daily: 60
      # Weekly backups: keep for 6 months
      weekly: 180  # 6 months
      # Monthly backups: keep for 3 years
      monthly: 1095  # 3 years
      # Delete everything older than 3 years
      max_age: 1095  # 3 years
  
  # Legacy retention setting (for backward compatibility)
  retention_days: 90
  
  # Remote storage configuration
  remote_storage:
    # Enable remote storage upload
    enabled: true
    
    # Remote storage type: 'webdav', 'ftp', or 'cifs'
    type: "webdav"
    
    # WebDAV configuration (for Nextcloud, OwnCloud, etc.)
    webdav:
      # WebDAV server URL
      url: "https://your-webdav-server.com/remote.php/dav/files/backup/production"
      
      # WebDAV username
      username: "your_webdav_username"
      
      # WebDAV password
      password: "your_webdav_password"
      
      # Verify SSL certificate (recommended: true)
      verify_ssl: true

# Database-specific logging settings
logging:
  # Logging level: DEBUG, INFO, WARNING, ERROR
  level: INFO
  
  # Path to log file (use absolute path for production)
  file: /var/log/postgresql_backup_production.log
